apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service
  namespace: argocd
spec:
  project: default
  source:
    chart: service
    repoURL: https://arkberezkin.github.io/charts/
    targetRevision: 0.1.1
    helm:
      releaseName: service
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default